# RelativeURLs=true
# CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AWS Public Sector AI/ML Virtual Loft"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
baseURL = "http://localhost:1313/"

# uglyurls = true
# sectionPagesMenu = "main"
# pygmentsCodeFences = true
# pygmentsStyle = "monokai"

[params]
  ordersectionsby = "weight"
  baseURL = "http://localhost:1313/"
  videoBaseUrl = "https://d3ezjgxqne0l2q.cloudfront.net/video/"
  description = "AWS Public Sector AI/ML Virtual Loft"
  topic = "Artificial Intelligence and Machine Learning"
  servicelist = "Amazon Sagemaker, Amazon Rekognition, Amazon Comprehend and Amazon Polly"
  cfregion = "ap-southeast-2"
  cfregiondisplay = "AP Southeast 2 (Sydney)"
  author = "Cain Hopwood"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "walabs"
  disableSearch = true
  disableAssetsBusting = true
  disableLanguageSwitchingButton = true
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true
  showVisitedLinks = true
  custom_css = ["/css/custom.css"]
  [aws_regions]
  "ap-southeast-2" = "AP Southeast 2 (Sydney)"
  "ap-southeast-1" = "Asia Pacific (Singapore)"
  "ap-south-1" = "Asia Pacific (Mumbai)"
    
[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[Languages]
[Languages.en]
title = "AWS Public Sector AI/ML Virtual Loft"
weight = 1
languageName = "English"

